// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5oxAr1mBFpHVg_qI7ghLQi_-SR62oAnY',
    appId: '1:792602781807:web:bda8917d020dd8d1b3859a',
    messagingSenderId: '792602781807',
    projectId: 'nawabs-app',
    authDomain: 'nawabs-app.firebaseapp.com',
    storageBucket: 'nawabs-app.appspot.com',
    measurementId: 'G-LPLM2EWBRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GdpK8UKEPlVABTyAoOhmpr5Ky_znqyo',
    appId: '1:792602781807:android:374ad199760325f2b3859a',
    messagingSenderId: '792602781807',
    projectId: 'nawabs-app',
    storageBucket: 'nawabs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBb15JnUZsWSaBEI9-g25vr1zwolGs0P0',
    appId: '1:792602781807:ios:ca82d00cc2f76ec6b3859a',
    messagingSenderId: '792602781807',
    projectId: 'nawabs-app',
    storageBucket: 'nawabs-app.appspot.com',
    iosClientId: '792602781807-oth3v7gu1okbnqt5ufbbne8rh89ibj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawaqs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBb15JnUZsWSaBEI9-g25vr1zwolGs0P0',
    appId: '1:792602781807:ios:ca82d00cc2f76ec6b3859a',
    messagingSenderId: '792602781807',
    projectId: 'nawabs-app',
    storageBucket: 'nawabs-app.appspot.com',
    iosClientId: '792602781807-oth3v7gu1okbnqt5ufbbne8rh89ibj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawaqs',
  );
}
